library(tidyverse)
library(lubridate)
library(hms)
library(scales)
library(broom)

# TODO: Figure out what to do with plant 4136001 (multiply by 10?)
# TODO: Check Correlation between weather sensor data and output
# TODO: Create validation set (last three days of the month)
# TODO: Create train and test set

################################################################################
# EXTRACT, TRANSFORM, LOAD
################################################################################

#Sources
#Power generation and sensor data gathered from two solar power plants

#Collection Methodology
#Power generation and sensor data gathered at 15 minutes intervals over a 34 day
#period. Generation data collected at inverter level, while the sensor data is at
#the plant level.

# This data has been gathered at two solar power plants in India over a 34 day 
# period. It has two pairs of files - each pair has one power generation 
# dataset and one sensor readings dataset. The power generation datasets are 
# gathered at the inverter level - each inverter has multiple lines of solar 
# panels attached to it. The sensor data is gathered at a plant level - single 

# Plant 1 is near Gandikotta, Andhra and Plant 2 is near Nasik, Maharashtra.

# array of sensors optimally placed at the plant.

# DATE_TIME: Date and time for each observation. Observations recorded at 15 minute intervals.
# Generation - SOURCE_KEY: In generation file stands for the inverter id.
# Weather - SOURCE_KEY: Stands for the sensor panel id. This will be common for the entire file because there's only one sensor panel for the plant.
# DC_POWER: Amount of DC power generated by the inverter (source_key) in this 15 minute interval. Units - kW.
# AC_POWER: Amount of AC power generated by the inverter (source_key) in this 15 minute interval. Units - kW.
# DAILY_YIELD: A cumulative sum of power generated on that day, till that point in time.
# TOTAL_YIELD: The total yield for the inverter till that point in time.
# AMBIENT_TEMPERATURE: This is the ambient temperature at the plant.
# MODULE_TEMPERATURE: There's a module (solar panel) attached to the sensor panel. This is the temperature reading for that module.
# IRRADIATION: Amount of irradiation for the 15 minute interval.

parse_generation_data <- function(file_name,
                                  date_format = "ymd HM",
                                  data_path = "./data/") {
  read.csv(paste0(data_path, file_name)) %>%
    as_tibble() %>%
    # For some reason, the two files use different date formatting
    mutate(date_time = parse_date_time(DATE_TIME, date_format),
           plant_id = as.character(PLANT_ID)) %>%
    select(-DATE_TIME, -PLANT_ID) %>%
    rename(source_key = SOURCE_KEY,
           dc_power = DC_POWER,
           ac_power = AC_POWER,
           daily_yield = DAILY_YIELD,
           total_yield = TOTAL_YIELD) %>%
    relocate(date_time,
             plant_id,
             source_key,
             dc_power,
             ac_power,
             daily_yield,
             total_yield)
}


parse_weather_data <- function(file_name, data_path = "./data/") {
  read.csv(paste0(data_path, file_name)) %>%
    as_tibble() %>%
    mutate(date_time = parse_date_time(DATE_TIME, ("ymd HMS")),
           plant_id = as.character(PLANT_ID)) %>%
    select(-DATE_TIME, -PLANT_ID) %>%
    rename(source_key = SOURCE_KEY,
           ambient_temperature = AMBIENT_TEMPERATURE,
           module_temperature = MODULE_TEMPERATURE,
           irradiation = IRRADIATION) %>%
    relocate(date_time,
             plant_id,
             source_key,
             ambient_temperature,
             module_temperature,
             irradiation)
}


generation <- 
  parse_generation_data("Plant_1_Generation_Data.csv", "dmy HM") %>%
  bind_rows(parse_generation_data("Plant_2_Generation_Data.csv", "ymd HMS"))


weather <- parse_weather_data("Plant_1_Weather_Sensor_Data.csv") %>%
  bind_rows(parse_weather_data("Plant_2_Weather_Sensor_Data.csv"))


# Contains a large number of NA rows,
#  and it is sometimes not useful to include them, or have a lot of 
#  na.remove = TRUE
solar <- generation %>%
  group_by(plant_id) %>%
  expand(date_time = full_seq(date_time, as.numeric(minutes(15))), 
         generation_source = source_key) %>%
  ungroup() %>%
  left_join(generation, by = c("date_time", 
                               "plant_id", 
                               "generation_source" = "source_key")) %>%
  full_join(weather, by = c("date_time", "plant_id")) %>%
  rename(weather_source = source_key)
  

head(generation)
dim(generation) # 136476      7
head(weather)
dim(weather) # 6441    6
head(solar)
dim(solar) # 143616     11
# Discrepency in row counts has to do with missing rows from generation data

object.size(generation)
object.size(weather)
object.size(solar)


rm(generation_sources, weather_sources, date_time, parse_generation_data, 
   parse_weather_data)




################################################################################
############################### EXPLORATION ####################################
################################################################################

#### DATE_TIME ####
range(solar$date_time) # "2020-05-15 00:00:00 UTC" "2020-06-17 23:45:00 UTC"
difftime(max(solar$date_time), min(solar$date_time)) # Time difference of 33.98958 days
n_distinct(solar$date_time) # 3264'

solar %>%
  anti_join(generation) %>%
  distinct(date_time) %>%
  nrow() # 1010

solar %>%
  anti_join(weather) %>%
  distinct(date_time) %>%
  nrow()# 85

#### PLANT_ID ####
unique(generation$plant_id) # 4135001 4136001
unique(weather$plant_id) # 4135001 4136001

solar %>%
  anti_join(generation) %>%
  ggplot(aes(x = date_time, fill = plant_id, color = plant_id)) +
  geom_bar() +
  xlim(range(generation$date_time)) +
  labs(title = "Time Series of Power Inverter Failures",
       x = "Time",
       y = "Number of Failures")
    

solar %>%
  anti_join(weather) %>%
  ggplot(aes(x = date_time, fill = plant_id, color = plant_id)) +
  geom_bar() +
  xlim(range(weather$date_time)) +
  labs(title = "Time Series of Weather Sensor Failures",
       x = "Time",
       y = "Number of Failures")


#### SOURCE_KEY ####
n_distinct(generation$source_key) # 44
n_distinct(weather$source_key) # 2

plant_1_source_keys <- 
  generation %>%
  filter(plant_id == "4135001") %>%
  pull(source_key) %>%
  unique()

plant_2_source_keys <- 
  generation %>%
  filter(plant_id == "4136001") %>%
  pull(source_key) %>%
  unique()

intersect(plant_1_source_keys, plant_2_source_keys) # character(0)

rm(plant_1_source_keys, plant_2_source_keys)

solar %>%
  anti_join(generation) %>%
  group_by(plant_id, generation_source) %>%
  tally() %>%
  ggplot(aes(x = reorder(generation_source, -n), y = n, fill = plant_id)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Inverter Failures",
       x = "Inverter",
       y = "Total Number of Failures")



################################################################################
######################     Generation Data      ################################
################################################################################

# DC Power
generation %>% 
  pull(dc_power) %>% 
  summary()

generation %>%
  ggplot(aes(x = dc_power))+
  geom_histogram()

generation %>%
  filter(dc_power > 0.0) %>%
  ggplot(aes(x = dc_power))+
  geom_histogram()

generation %>%
  summarize(no_dc_rate = mean(dc_power == 0)) # 0.495


# AC Power
generation %>% 
  pull(ac_power) %>% 
  summary()

generation %>%
  ggplot(aes(x = ac_power))+
  geom_histogram()

generation %>%
  filter(ac_power > 0.0) %>%
  ggplot(aes(x = ac_power))+
  geom_histogram()

generation %>%
  summarize(no_ac_rate = mean(ac_power == 0)) # 0.495


# Daily Yield
generation %>% 
  pull(daily_yield) %>% 
  summary()

generation %>%
  ggplot(aes(x = daily_yield))+
  geom_histogram()

generation %>%
  filter(daily_yield > 0.0) %>%
  ggplot(aes(x = daily_yield))+
  geom_histogram()

generation %>%
  summarize(no_daily_yield_rate = mean(daily_yield == 0)) # 0.222

# Total Yield
generation %>% 
  pull(total_yield) %>% 
  summary()

generation %>%
  ggplot(aes(x = total_yield))+
  geom_histogram()

generation %>%
  filter(total_yield > 0.3) %>%
  ggplot(aes(x = total_yield))+
  geom_histogram() +
  scale_x_log10()

generation %>%
  summarize(no_total_yield_rate = mean(total_yield == 0)) # 0.00413

################################################################################
################################### Averages ###################################
################################################################################

# View entire month average by plant
generation %>%
  group_by(date_time, plant_id) %>%
  summarize(avg_dc_power = mean(dc_power)) %>%
  group_by(plant_id) %>%
  ggplot(aes(x = date_time, y = avg_dc_power, color = plant_id)) +
  geom_line()

# view all sources for one day
generation %>%
  filter(date_time < make_date(2020, 05, 16)) %>%
  group_by(date_time, plant_id) %>%
  summarize(avg_dc_power = mean(dc_power)) %>%
  group_by(plant_id) %>%
  ggplot(aes(x = date_time, y = avg_dc_power, fill = plant_id)) +
  geom_area(position = "stack") +
  theme(legend.position = "none")


# view one day from one source
generation %>%
  filter(source_key == unique(source_key)[1]) %>%
  filter(date_time < make_date(2020, 05, 16)) %>%
  ggplot(aes(x = date_time, y = dc_power)) +
  geom_area()


################################################################################
######################       Weather Data     ##################################
################################################################################

# Ambient Temperature
weather %>%
  pull(ambient_temperature) %>%
  summary()

weather %>%
  ggplot(aes(x = ambient_temperature)) +
  geom_histogram(bins = 40)

# Module Temperature
weather %>%
  pull(module_temperature) %>%
  summary()

weather %>%
  ggplot(aes(x = module_temperature)) +
  geom_histogram(bins = 40)

# Irradiation
weather %>%
  pull(irradiation) %>%
  summary()

weather %>%
  ggplot(aes(x = irradiation)) +
  geom_histogram(bins = 40)

weather %>%
  filter(irradiation > 0.00001) %>%
  ggplot(aes(x = irradiation)) +
  geom_histogram(bins = 40)

weather %>%
  summarize(no_irradiation_rate = mean(irradiation == 0)) # 0.438

################################################################################
################################### Averages ###################################
################################################################################

# view entire month from both sources
weather %>%
  group_by(plant_id) %>%
  ggplot(aes(x = date_time, y = ambient_temperature, color = plant_id)) +
  geom_line()

weather %>%
  group_by(plant_id) %>%
  ggplot(aes(x = date_time, y = module_temperature, color = plant_id)) +
  geom_line()

weather %>%
  group_by(plant_id) %>%
  ggplot(aes(x = date_time, y = irradiation, color = plant_id)) +
  geom_line()


################################################################################
################################# CORRELATION ##################################
################################################################################


#### AC Power vs DC Power ####

generation %>%
  ggplot(aes(x = dc_power, y = ac_power, color = plant_id)) +
  geom_point(alpha = 0.25)

plant_ids <- generation %>%
  distinct(plant_id) %>%
  pull(plant_id)

get_lse <- function(x, y){
  fit <- lm(y ~ x)
  tibble(term = names(fit$coefficients),
         slope = fit$coefficients, 
         se = summary(fit)$coefficient[,2])
}

fit <- generation %>%
  group_by(plant_id) %>%
  summarize(get_lse(dc_power, ac_power))

plant_1_fit <- generation %>%
  filter(plant_id == plant_ids[1]) %>%
  lm(ac_power ~ dc_power, data = .) %>%
  tidy()

plant_2_fit <- generation %>%
  filter(plant_id == plant_ids[2]) %>%
  lm(ac_power ~ dc_power, data = .) %>%
  tidy()

generation %>%
  ggplot(aes(x = dc_power, y = ac_power, color = plant_id)) +
  geom_point(alpha = 0.25) +
  geom_abline(slope = plant_1_fit$estimate[2], 
              intercept = plant_1_fit$estimate[1],
              size = 1) +
  geom_abline(slope = plant_2_fit$estimate[2],
              intercept = plant_2_fit$estimate[1],
              size = 1) +
  labs(title = "AC Power Produced per DC Power In",
       x = "DC Power",
       y = "AC Power")


#### 

weather %>%
  filter(plant_id == plant_ids[1]) %>%
  mutate(time = as_datetime(as_hms(date_time))) %>%
  group_by(time) %>%
  ggplot(aes(x = ambient_temperature, y = module_temperature, color = time)) +
  geom_point()

weather %>%
  filter(plant_id == plant_ids[2]) %>%
  mutate(time = as_datetime(as_hms(date_time))) %>%
  group_by(time) %>%
  ggplot(aes(x = ambient_temperature, y = module_temperature, color = time)) +
  geom_point()

weather %>%
  filter(plant_id == plant_ids[1]) %>%
  mutate(time = as_datetime(as_hms(date_time))) %>%
  group_by(time) %>%
  ggplot(aes(x = irradiation, y = module_temperature, color = time)) +
  geom_point() 

weather %>%
  filter(plant_id == plant_ids[2]) %>%
  mutate(time = as_datetime(as_hms(date_time))) %>%
  group_by(time) %>%
  ggplot(aes(x = irradiation, y = module_temperature, color = time)) +
  geom_point() 

weather %>%
  filter(plant_id == plant_ids[1]) %>%
  mutate(time = as_datetime(as_hms(date_time))) %>%
  group_by(time) %>%
  ggplot(aes(x = irradiation, y = module_temperature, color = time)) +
  geom_point()

weather %>%
  filter(plant_id == plant_ids[2]) %>%
  mutate(time = as_datetime(as_hms(date_time))) %>%
  group_by(time) %>%
  ggplot(aes(x = irradiation, y = module_temperature, color = time)) +
  geom_point()

weather %>%
  filter(plant_id == plant_ids[1]) %>%
  mutate(time = as_datetime(as_hms(date_time))) %>%
  group_by(time) %>%
  ggplot(aes(x = irradiation, y = ambient_temperature, color = time)) +
  geom_point()

weather %>%
  filter(plant_id == plant_ids[2]) %>%
  mutate(time = as_datetime(as_hms(date_time))) %>%
  group_by(time) %>%
  ggplot(aes(x = irradiation, y = ambient_temperature, color = time)) +
  geom_point()

weather %>%
  filter(plant_id == plant_ids[1]) %>%
  mutate(date = round_date(date_time, unit = "day"),
         time = make_datetime(0, 0, 0, hour(date_time), minute(date_time))) %>%
  group_by(date) %>%
  ggplot(aes(x = time, y = ambient_temperature, group = date, color = date)) +
  geom_line(alpha = 0.5) +
  scale_x_datetime(labels = date_format("%H:%M")) +
  labs(title = "Ambient Temperature of Time",
       x = "Time",
       y = "Ambient Temperature (Degrees Celsius)") +
  ylim(c(15, 40)) +
  theme(legend.position = "none")
  

weather %>%
  filter(plant_id == plant_ids[2]) %>%
  mutate(date = round_date(date_time, unit = "day"),
         time = make_datetime(0, 0, 0, hour(date_time), minute(date_time))) %>%
  group_by(date) %>%
  ggplot(aes(x = time, y = ambient_temperature, group = date, color = date)) +
  geom_line(alpha = 0.5) +
  scale_x_datetime(labels = date_format("%H:%M")) +
  labs(title = "Ambient Temperature of Time",
       x = "Time",
       y = "Ambient Temperature (Degrees Celsius)") +
  ylim(c(15, 40)) +
  theme(legend.position = "none")

  

### FROM THIS: I am going to conclude that temperature is highly, highly correlated
### to irradition and time. Thus, it will not be included with original predictions
### Additionally, it is shown that ac_power is highly correlated to dc_power, 
### but both plants must be considered differently for that.

solar %>%
  group_by(plant_id) %>%
  ggplot(aes(irradiation, ac_power, color = plant_id)) +
  geom_point()

solar %>%
  group_by(plant_id) %>%
  ggplot(aes(irradiation, dc_power, color = plant_id)) +
  geom_point()

solar %>%
  group_by(plant_id) %>%
  ggplot(aes(module_temperature, dc_power, color = plant_id)) +
  geom_point(alpha = 0.25)
